name: Update XKCD Comic

on:
  # run at 12 AM MYT (UTC+8)
  schedule:
  - cron: "0 4 * * *"
  
  # allows this action to manually run the job
  workflow_dispatch:
  # run on every push on the main branch
  push:
    branches:
    - main
    
jobs:
  update_xkcd:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      
      - name: Generate random comic number
        id: comic
        run: |
          # Generates a number between 10 - 3000
          COMIC_NUM=$(shuf -i 10-3000 -n 1)
          
          # Get comic data
          COMIC_DATA=$(curl -s "https://xkcd.com/$COMIC_NUM/info.0.json")
          TITLE=$(echo "$COMIC_DATA" | jq -r '.title')
          IMG_URL=$(echo "$COMIC_DATA" | jq -r '.img')

          echo "COMIC_NUM=$COMIC_NUM" >> $GITHUB_ENV
          echo "TITLE=$TITLE" >> $GITHUB_ENV
          echo "IMG_URL=$IMG_URL" >> $GITHUB_ENV
          
      - name: Update on Readme.md
        run: |
          section_start="<!-- XKCD_START -->"
          section_end="<!-- XKCD_END -->"
          new_content="![XKCD Comic]('${IMG_URL}')"

          awk -v start="$section_start" -v end="$section_end" -v content="$new_content" '
            $0==start {print; print content; f=1; next}
            $0==end {f=0}
            !f
          ' README.md > temp.md && mv temp.md README.md

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git add README.md
          git commit -m "Update README section" || echo "Daily XKCD Comic Update"
          git push
          
