name: Update XKCD Comic

on:
  # run at 12 AM MYT (UTC+8)
  schedule:
  - cron: "0 4 * * *"
  
  # allows this action to manually run the job
  workflow_dispatch:
  # run on every push on the main branch
  push:
    branches:
    - main
    
jobs:
  update_xkcd:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      
      - name: Generate random comic number
        id: comic
        run: |
          # Generates a number between 10 - 3000
          COMIC_NUM=$(shuf -i 10-3000 -n 1)
          
          # Get comic data
          COMIC_DATA=$(curl -s "https://xkcd.com/$COMIC_NUM/info.0.json")
          TITLE=$(echo "$COMIC_DATA" | jq -r '.title')
          IMG_URL=$(echo "$COMIC_DATA" | jq -r '.img')

          echo "COMIC_NUM=$COMIC_NUM" >> $GITHUB_ENV
          echo "TITLE=$TITLE" >> $GITHUB_ENV
          echo "IMG_URL=$IMG_URL" >> $GITHUB_ENV
          
      - name: Update on Readme.md
        run: |
          BLOCK="[![${TITLE}](${IMG_URL})](https://xkcd.com/${COMIC_NUM}/)\n"
          echo "$BLOCK" > block.txt
          perl -0777 -pe '{
            local $/;
            open my $fh, "<", "block.txt";
            my $block = do { local $/; <$fh> };
            s/<!-- XKCD START -->.*?<!-- XKCD END -->/<!-- XKCD START -->\n$block\n<!-- XKCD END -->/s
          }' README.md > README.md.new
          mv README.md.new README.md
          
